# 2. mājas darbs

### 1. Saraksti

In [1]:
# Izveidot sarakstu x ar savu studenta numuru
x = ['b', 0, 1, 6, 0, 0, 8]

# Izdrukāt pirmo un pēdējo simbolu
print(f"Pirmais simbols: {x[0]}")
print(f"Pēdējais simbols: {x[-1]}")

Pirmais simbols: b
Pēdējais simbols: 8


In [2]:
# Izveidot x saraksta kopiju y un pievienot sākumā jaunu elementu
y = x.copy()
y.insert(0, 9)

# Izņemt no saraksta y visus elementus kas nav cipari
y = [i for i in y if isinstance(i, int)]
print(f"Saraksts y: {y}")

Saraksts y: [9, 0, 1, 6, 0, 0, 8]


### 2. Numpy

In [3]:
import numpy as np

In [4]:
# Izveidot numpy masīvu ar studenta numura cipariem
arr = np.array([0, 1, 6, 0, 0, 8])

In [5]:
# Pievienot masīva arr beigās elementu
arr = np.append(arr, sum(arr))
print(f"Masīvs ar summu: {arr}")

Masīvs ar summu: [ 0  1  6  0  0  8 15]


**Pieņēmums:** masīvu nevajag kārtot.

In [6]:
# Izdrukāt vidējo masīva arr elementu
if len(arr) % 2 == 0:
    print(f"Vidējie elementi: {arr[len(arr) // 2 - 1 : len(arr) // 2 + 1]}")
else:
    print(f"Vidējais elements: {arr[len(arr) // 2]}")

Vidējais elements: 0


In [7]:
# Izdrukāt masīva arr izmērus
print(f"Masīva izmērs: {arr.shape}")

Masīva izmērs: (7,)


**Pieņēmums**: otro kolonnu aizpildam ar nullem.

In [8]:
# Pārmainīt masīva arr izmēru
arr_reshaped = np.column_stack((arr, np.zeros_like(arr)))
print(f"Masīvs ar 2 kolonnām: {arr_reshaped}")

Masīvs ar 2 kolonnām: [[ 0  0]
 [ 1  0]
 [ 6  0]
 [ 0  0]
 [ 0  0]
 [ 8  0]
 [15  0]]


In [9]:
# Izveidot divus numpy masīvus
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

In [10]:
# Saskaitīt arr1 un arr2 masīvu vērtības
rez = arr1 + arr2
print(f"Rezultāts: {rez}")

Rezultāts: [ 6  8 10 12]


In [11]:
# Aprēķināt un izdrukāt rez masīva saturošo skaitļu vidējo vērtību
print(f"Vidējā vērtība: {np.mean(rez)}")

Vidējā vērtība: 9.0


In [12]:
# Aprēķināt masīva (vektora) arr garumu
print(f"Vektora garums: {np.linalg.norm(arr)}")

Vektora garums: 18.05547008526779


### 3. Lineārā algebra 1

In [13]:
# Izveidot no jauna numpy masīvu ar studenta numura cipariem
arr = np.array([0, 1, 6, 0, 0, 8])

# Izveidot numpy vienības matricu
vienibas_matrica = np.eye(len(arr))

In [14]:
# Izveidot numpy matricu ar studenta numura cipariem
mat = np.tile(arr, (len(arr), 1))
print(f"Matrica: {mat}")

Matrica: [[0 1 6 0 0 8]
 [0 1 6 0 0 8]
 [0 1 6 0 0 8]
 [0 1 6 0 0 8]
 [0 1 6 0 0 8]
 [0 1 6 0 0 8]]


In [15]:
# Aprēķināt matricas determinantu
determinant = np.linalg.det(mat)
print(f"Determinants: {determinant}")

Determinants: 0.0


In [16]:
# Veikt matricu reizinājumu
product = np.matmul(mat, vienibas_matrica)
print(f"Reizinājuma rezultāts: {product}")

Reizinājuma rezultāts: [[0. 1. 6. 0. 0. 8.]
 [0. 1. 6. 0. 0. 8.]
 [0. 1. 6. 0. 0. 8.]
 [0. 1. 6. 0. 0. 8.]
 [0. 1. 6. 0. 0. 8.]
 [0. 1. 6. 0. 0. 8.]]


### 4. Lineārā algebra 2

In [17]:
from scipy.linalg import eig

In [18]:
# Izveidot jaunu neatkarīgu mainīgo
ev = mat.copy()

In [19]:
# Nomainīt masīva ev otrās rindas pēdējās kolonnas vērtību
ev[1,-1] = 9

In [20]:
# Aprēķināt matricas ev īpašvērtības un īpašvektorus
eigenvalues, eigenvectors = eig(ev)

print(f"Īpašvērtības: {eigenvalues}")
print(f"Īpašvektori: {eigenvectors}")

Īpašvērtības: [ 0.        +0.j  0.        +0.j  0.        +0.j -0.06637298+0.j
 15.06637298+0.j  0.        +0.j]
Īpašvektori: [[ 1.00000000e+000  0.00000000e+000  0.00000000e+000  7.02099623e-002
   4.03660807e-001  5.77350269e-001]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 -9.87599517e-001
   4.30452976e-001  3.16786038e-276]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  7.02099623e-002
   4.03660807e-001 -5.27976729e-277]
 [ 0.00000000e+000  1.00000000e+000  0.00000000e+000  7.02099623e-002
   4.03660807e-001  5.77350269e-001]
 [ 0.00000000e+000  0.00000000e+000  1.00000000e+000  7.02099623e-002
   4.03660807e-001  5.77350269e-001]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  7.02099623e-002
   4.03660807e-001  3.27444051e-291]]
